# Generated by Django 2.1.7 on 2019-02-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('genre', models.CharField(choices=[('ac', 'Action'), ('fc', 'Fiction'), ('ad', 'Adventure'), ('cm', 'Comedy'), ('dr', 'Drama'), ('ro', 'Romance')], default='ac', max_length=2)),
                ('sinopsis', models.TextField()),
                ('release', models.DateField()),
                ('runtime', models.PositiveIntegerField()),
                ('rating', models.PositiveIntegerField()),
                ('poster', models.ImageField(upload_to='media')),
            ],
        ),
    ]
